require('lze').load {
  { import = 'plugins.which-key' },
  { import = 'plugins.snacks' },
  -- { import = 'plugins.typescript-tools' },
  { import = 'plugins.completion' },
  { import = 'plugins.tokyonight' },
  { import = 'plugins.conform' },
  { import = 'plugins.git' },
  { import = 'plugins.nvim-dap' },
  { import = 'plugins.noice' },
  { import = 'plugins.dashboard' },
  { import = 'plugins.eyeliner' },
  { import = 'plugins.rainbow' },
  { import = 'plugins.lualine' },
  { import = 'plugins.undotree' },
  { import = 'plugins.navic' },
  { import = 'plugins.gitsigns' },
  { import = 'plugins.oil' },
  { import = 'plugins.mini' },
  { import = 'plugins.neominimap' },
  { import = 'plugins.autopairs' },
  { import = 'plugins.leetcode' },
}
vim.cmd([[colorscheme tokyonight-night]])
